### ISSUE TITLE
n_chunks Settings

### ISSUE THREAD

**Issue by zhengzich2020** [tglauch/pyVPRM#2]
Hello, 
Thank you very much for the code you provided. 
How should I effectively and correctly set n_cpus,n_chunks, chunk_x and chunk_y when I run it? 
There are some errors in the result after I set these parameters.

**Comment by tglauch** [comment]
Hi,
Thanks for you question. I assume you are referring to one of the scripts in the example repository ([https://github.com/tglauch/pyVPRM_examples])?!  Note that all of these scripts are only one possible way to use the pyVPRM framework. 

In those examples the ``n_chunks`` parameter in the config files defines the number of chunks in each dimension. Consequently if you use ``n_chunks = 2`` you'll need to run 4 scripts with:

--chunk_x  1 --chunk_y 1
--chunk_x  1 --chunk_y 2
--chunk_x  2 --chunk_y 2
--chunk_x  2 --chunk_y 1

Hope this clarifies the usage of those scripts.
